package dev.slne.surf.microservice.gradle.plugin

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.SetProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/** Generates a deterministic, dependency-aware Dockerfile for a runnable Surf microservice. */
@DisableCachingByDefault(because = "Generation is inexpensive and must preserve manual Dockerfile overwrite protection.")
abstract class GenerateMicroserviceDockerfile : DefaultTask() {
    /** Destination of the generated Dockerfile. */
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    /** Whether a non-generated destination file may be replaced. */
    @get:Input
    abstract val overwrite: Property<Boolean>

    /** Runtime image used by the final container stage. */
    @get:Input
    abstract val baseImage: Property<String>

    /** JDK image used by the Gradle build stage. */
    @get:Input
    abstract val builderImage: Property<String>

    /** Name of the existing task that creates the runnable application JAR. */
    @get:Input
    abstract val runnableTaskName: Property<String>

    /** Runnable JAR path relative to the consuming project directory. */
    @get:Input
    abstract val runnableArtifactPath: Property<String>

    /** Resolved runtime module coordinates used to select environment contracts. */
    @get:Input
    abstract val runtimeDependencies: SetProperty<String>

    /** Writes the configured Dockerfile. */
    @TaskAction
    fun generate() {
        val destination = outputFile.get().asFile
        protectExistingFile(destination)

        val artifactPath = runnableArtifactPath.get().replace('\\', '/')
        if (artifactPath.startsWith("../") || artifactPath.startsWith('/')) {
            throw GradleException(
                "The runnable artifact must be inside the Docker build context: $artifactPath"
            )
        }

        val dependencies = runtimeDependencies.get()
        val rabbitMQ = dependencies.any { it.substringBefore(':') == DockerEnvironmentContracts.RABBITMQ_GROUP }
        val database = dependencies.any {
            it == "${DockerEnvironmentContracts.DATABASE_GROUP}:${DockerEnvironmentContracts.DATABASE_MODULE}"
        }

        destination.parentFile?.mkdirs()
        destination.writeText(
            dockerfile(artifactPath, rabbitMQ, database),
            Charsets.UTF_8,
        )
    }

    private fun protectExistingFile(destination: java.io.File) {
        if (!destination.exists() || overwrite.get()) return
        if (destination.readText(Charsets.UTF_8).lineSequence().any { it == GENERATED_MARKER }) return

        throw GradleException(
            "Refusing to overwrite ${destination.absolutePath} because it was not generated by " +
                    "${path}. Move the file, add the generated marker, or set " +
                    "surfMicroservice.docker.overwrite to true."
        )
    }

    private fun dockerfile(artifactPath: String, rabbitMQ: Boolean, database: Boolean): String = buildString {
        appendLine("# syntax=docker/dockerfile:1")
        appendLine(GENERATED_MARKER)
        appendLine("FROM ${builderImage.get()} AS build")
        appendLine("WORKDIR /workspace")
        appendLine("COPY . .")
        appendLine("RUN chmod +x gradlew && ./gradlew ${runnableTaskName.get()} --no-daemon")
        appendLine()
        appendLine("FROM ${baseImage.get()}")
        appendLine("RUN groupadd --system --gid 10001 app && \\")
        appendLine("    useradd --system --uid 10001 --gid app --home-dir /app --create-home app")
        appendLine("WORKDIR /app")
        appendLine("COPY --from=build --chown=app:app /workspace/$artifactPath /app/app.jar")
        appendLine("ENV JAVA_OPTS=\"\"")

        if (rabbitMQ) appendEnvironmentSection("RabbitMQ", DockerEnvironmentContracts.rabbitMQ)
        if (database) appendEnvironmentSection("Database", DockerEnvironmentContracts.database)

        appendLine("USER app")
        appendLine(
            "ENTRYPOINT [\"sh\", \"-c\", \"exec java ${'$'}JAVA_OPTS -jar /app/app.jar \\\"${'$'}@\\\"\", \"--\"]"
        )
    }

    private fun StringBuilder.appendEnvironmentSection(
        title: String,
        variables: List<EnvironmentVariableDescriptor>,
    ) {
        appendLine()
        appendLine("# $title runtime environment (configure in Coolify; values are not embedded):")
        variables.forEach { variable ->
            val secretSuffix = if (variable.secret) "; configure as a secret" else ""
            appendLine("# - ${variable.name}: ${variable.description}$secretSuffix")
        }
    }

    private companion object {
        const val GENERATED_MARKER =
            "# Generated by dev.slne.surf.microservice (generateMicroserviceDockerfile)."
    }
}
