package dev.slne.surf.microservice.gradle.plugin

import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import org.gradle.api.GradleException
import org.gradle.api.provider.Provider
import java.io.File

internal const val DOCKER_APPLICATION_JAR_NAME = "app.jar"

private const val BUILD_STAGE_NAME = "build"
private const val APPLICATION_USER = "app"
private const val APPLICATION_GROUP = "app"
private const val APPLICATION_UID = 10_001
private const val APPLICATION_GID = 10_001

private const val GENERATED_MARKER =
    "# Generated by dev.slne.surf.microservice (generateMicroserviceDockerfile)."

internal fun Dockerfile.configureMicroserviceDockerfile(
    overwrite: Provider<Boolean>,
    builderImage: Provider<String>,
    baseImage: Provider<String>,
    runnableTaskPath: Provider<String>,
    runnableArtifactPath: Provider<String>,
    runtimeDependencies: Provider<Set<String>>,
) {
    val dockerfileTask = this

    inputs.property("surfMicroservice.docker.overwrite", overwrite)

    outputs.doNotCacheIf(
        "Generation must preserve manual Dockerfile overwrite protection."
    ) {
        true
    }

    doFirst {
        val destination = dockerfileTask.destFile.get().asFile

        destination.parentFile?.mkdirs()
        protectExistingDockerfile(destination, overwrite.get(), dockerfileTask.path)
    }

    instruction("# syntax=docker/dockerfile:1")
    instruction(GENERATED_MARKER)

    from(
        builderImage.map { image ->
            Dockerfile.From(image).apply {
                withStage(BUILD_STAGE_NAME)
            }
        }
    )

    workingDir("/workspace")
    copyFile(".", ".")

    runCommand(
        runnableTaskPath.map { task ->
            "chmod +x gradlew && ./gradlew $task --no-daemon"
        }
    )

    from(
        baseImage.map { image ->
            Dockerfile.From(image)
        }
    )

    runCommand(buildString {
        append("groupadd --system --gid $APPLICATION_GID $APPLICATION_GROUP")
        append(" && ")
        append("useradd --system --uid $APPLICATION_UID --gid $APPLICATION_GROUP --home-dir /app --create-home $APPLICATION_USER")
    })

    workingDir("/app")

    copyFile(
        runnableArtifactPath.map { artifactPath ->
            Dockerfile.CopyFile(
                "/workspace/${artifactPath.asDockerContextPath()}",
                "/app/$DOCKER_APPLICATION_JAR_NAME"
            ).apply {
                withStage(BUILD_STAGE_NAME)
                withChown("$APPLICATION_USER:$APPLICATION_GROUP")
            }
        }
    )

    environmentVariable("JAVA_OPTS", "")

    DockerEnvironmentContract.entries.forEach { contract ->
        instruction(
            runtimeDependencies.map { dependencies ->
                if (contract.isRequiredBy(dependencies)) {
                    "#\n${contract.renderDocumentation()}"
                } else {
                    ""
                }
            }
        )
    }

    user(APPLICATION_USER)

    entryPoint(
        "sh",
        "-c",
        $$"exec java $JAVA_OPTS " +
                "-jar /app/$DOCKER_APPLICATION_JAR_NAME " +
                "\"$@\"",
        "--"
    )
}

internal fun File.relativeToDockerContext(
    contextDirectory: File,
): String {
    val contextPath = contextDirectory
        .toPath()
        .toAbsolutePath()
        .normalize()

    val targetPath = toPath()
        .toAbsolutePath()
        .normalize()

    if (!targetPath.startsWith(contextPath)) {
        throw GradleException(
            "The runnable artifact must be inside the Docker build context: $targetPath"
        )
    }

    return contextPath
        .relativize(targetPath)
        .toString()
        .replace(File.separatorChar, '/')
}

private fun String.asDockerContextPath(): String {
    val normalized = replace('\\', '/').removePrefix("./")

    val invalid =
        normalized.isBlank() ||
                normalized.startsWith('/') ||
                normalized.split('/').any { segment -> segment == ".." }

    if (invalid) {
        throw GradleException(
            "The runnable artifact must be inside the Docker build context: $this"
        )
    }

    return normalized
}

private fun protectExistingDockerfile(
    destination: File,
    overwrite: Boolean,
    taskPath: String,
) {
    if (!destination.exists() || overwrite) {
        return
    }

    val generated = destination.useLines(Charsets.UTF_8) { lines ->
        lines.any { line -> line == GENERATED_MARKER }
    }

    if (generated) {
        return
    }

    throw GradleException(
        "Refusing to overwrite ${destination.absolutePath} because it was not generated by " +
                "$taskPath. Move the file, add the generated marker, or set " +
                "surfMicroservice.docker.overwrite to true."
    )
}